name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      run: sudo apt update && sudo apt install cmake
    - name: Configure and build
      run: |
        rm -rf _build
        cmake -H. -B_build
        cmake --build _build
